# -*- coding: utf-8 -*-
"""Data Cleaning & Visualization Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhqdKsixO52v6MPvhUrULTsu0GWFY8A8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("dirty_cafe_sales.csv")

print(df.head())
print(df.info())

print(df.isnull().sum())

df.replace(["ERROR", "UNKNOWN"], np.nan, inplace=True)

numeric_cols = ["Quantity", "Price Per Unit", "Total Spent"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df["Quantity"].fillna(df["Quantity"].median(), inplace=True)
df["Price Per Unit"].fillna(df["Price Per Unit"].median(), inplace=True)
df["Total Spent"].fillna(df["Total Spent"].median(), inplace=True)

df["Item"].fillna(df["Item"].mode()[0], inplace=True)
df["Payment Method"].fillna(df["Payment Method"].mode()[0], inplace=True)
df["Location"].fillna(df["Location"].mode()[0], inplace=True)

df.drop_duplicates(inplace=True)

df["Transaction Date"] = pd.to_datetime(df["Transaction Date"])

df["Month"] = df["Transaction Date"].dt.month
df["Day"] = df["Transaction Date"].dt.day_name()

plt.figure(figsize=(8,5))
sns.countplot(x="Item", data=df)
plt.title("Most Sold Items")
plt.xticks(rotation=45)
plt.show()

df["Payment Method"].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Payment Method Distribution")
plt.ylabel("")
plt.show()

sales = df.groupby("Item")["Total Spent"].sum()

sales.plot(kind='bar')
plt.title("Total Revenue by Item")
plt.ylabel("Revenue")
plt.show()

plt.figure(figsize=(8,5))

sns.heatmap(
    df[["Quantity", "Price Per Unit", "Total Spent"]].corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

daily_sales = df.groupby("Transaction Date")["Total Spent"].sum()

daily_sales.plot(figsize=(12,5))
plt.title("Daily Sales Trend")
plt.ylabel("Sales")
plt.show()